//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeHolder.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StakeholderDBEntities : DbContext
    {
        public StakeholderDBEntities()
            : base("name=StakeholderDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccountStatu> tblAccountStatus { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblCompanyShare> tblCompanyShares { get; set; }
        public virtual DbSet<tblRequestStatu> tblRequestStatus { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblSharePriceHistory> tblSharePriceHistories { get; set; }
        public virtual DbSet<tblUploadDocument> tblUploadDocuments { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserShareSale> tblUserShareSales { get; set; }
        public virtual DbSet<tblUserShareSalesApprover> tblUserShareSalesApprovers { get; set; }
        public virtual DbSet<tblUserShareTransactionHistory> tblUserShareTransactionHistories { get; set; }
        public virtual DbSet<tblUsersShareSalesRequest> tblUsersShareSalesRequests { get; set; }
        public virtual DbSet<tblUsersToken> tblUsersTokens { get; set; }
    }
}
