//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsersShareSalesRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsersShareSalesRequest()
        {
            this.tblUserShareSalesApprovers = new HashSet<tblUserShareSalesApprover>();
            this.tblUserShareTransactionHistories = new HashSet<tblUserShareTransactionHistory>();
        }
    
        public int UserShareSalesRequestId { get; set; }
        public int UserShareSalesId { get; set; }
        public Nullable<int> RequestUserId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> RequestStatusId { get; set; }
        public Nullable<int> NoOfShares { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> RequestUsersId { get; set; }
    
        public virtual tblRequestStatu tblRequestStatu { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        public virtual tblUser tblUser3 { get; set; }
        public virtual tblUserShareSale tblUserShareSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareSalesApprover> tblUserShareSalesApprovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareTransactionHistory> tblUserShareTransactionHistories { get; set; }
    }
}
