//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblCompanies = new HashSet<tblCompany>();
            this.tblCompanies1 = new HashSet<tblCompany>();
            this.tblCompanyShares = new HashSet<tblCompanyShare>();
            this.tblCompanyShares1 = new HashSet<tblCompanyShare>();
            this.tblRequestStatus = new HashSet<tblRequestStatu>();
            this.tblRequestStatus1 = new HashSet<tblRequestStatu>();
            this.tblSharePriceHistories = new HashSet<tblSharePriceHistory>();
            this.tblSharePriceHistories1 = new HashSet<tblSharePriceHistory>();
            this.tblUploadDocuments = new HashSet<tblUploadDocument>();
            this.tblUploadDocuments1 = new HashSet<tblUploadDocument>();
            this.tblUploadDocuments2 = new HashSet<tblUploadDocument>();
            this.tblUsers1 = new HashSet<tblUser>();
            this.tblUsers11 = new HashSet<tblUser>();
            this.tblUserShareSales = new HashSet<tblUserShareSale>();
            this.tblUserShareSales1 = new HashSet<tblUserShareSale>();
            this.tblUserShareSales2 = new HashSet<tblUserShareSale>();
            this.tblUserShareSalesApprovers = new HashSet<tblUserShareSalesApprover>();
            this.tblUserShareSalesApprovers1 = new HashSet<tblUserShareSalesApprover>();
            this.tblUserShareSalesApprovers2 = new HashSet<tblUserShareSalesApprover>();
            this.tblUserShareSalesApprovers3 = new HashSet<tblUserShareSalesApprover>();
            this.tblUserShareTransactionHistories = new HashSet<tblUserShareTransactionHistory>();
            this.tblUserShareTransactionHistories1 = new HashSet<tblUserShareTransactionHistory>();
            this.tblUserShareTransactionHistories2 = new HashSet<tblUserShareTransactionHistory>();
            this.tblUserShareTransactionHistories3 = new HashSet<tblUserShareTransactionHistory>();
            this.tblUserShareTransactionHistories4 = new HashSet<tblUserShareTransactionHistory>();
            this.tblUsersShareSalesRequests = new HashSet<tblUsersShareSalesRequest>();
            this.tblUsersShareSalesRequests1 = new HashSet<tblUsersShareSalesRequest>();
            this.tblUsersShareSalesRequests2 = new HashSet<tblUsersShareSalesRequest>();
            this.tblUsersShareSalesRequests3 = new HashSet<tblUsersShareSalesRequest>();
            this.tblUsersTokens = new HashSet<tblUsersToken>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string PasswordHash { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string ProfileImageURL { get; set; }
        public Nullable<int> AccountStatusId { get; set; }
        public string AdminComment { get; set; }
        public bool IsEmailVerified { get; set; }
        public bool IsAdmin { get; set; }
        public int AccessFailedCount { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    
        public virtual tblAccountStatu tblAccountStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompany> tblCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompany> tblCompanies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompanyShare> tblCompanyShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompanyShare> tblCompanyShares1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequestStatu> tblRequestStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequestStatu> tblRequestStatus1 { get; set; }
        public virtual tblRole tblRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSharePriceHistory> tblSharePriceHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSharePriceHistory> tblSharePriceHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUploadDocument> tblUploadDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUploadDocument> tblUploadDocuments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUploadDocument> tblUploadDocuments2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUser> tblUsers1 { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUser> tblUsers11 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareSale> tblUserShareSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareSale> tblUserShareSales1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareSale> tblUserShareSales2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareSalesApprover> tblUserShareSalesApprovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareSalesApprover> tblUserShareSalesApprovers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareSalesApprover> tblUserShareSalesApprovers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareSalesApprover> tblUserShareSalesApprovers3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareTransactionHistory> tblUserShareTransactionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareTransactionHistory> tblUserShareTransactionHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareTransactionHistory> tblUserShareTransactionHistories2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareTransactionHistory> tblUserShareTransactionHistories3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareTransactionHistory> tblUserShareTransactionHistories4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsersShareSalesRequest> tblUsersShareSalesRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsersShareSalesRequest> tblUsersShareSalesRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsersShareSalesRequest> tblUsersShareSalesRequests2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsersShareSalesRequest> tblUsersShareSalesRequests3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsersToken> tblUsersTokens { get; set; }
    }
}
