//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUploadDocument
    {
        public int UploadDocumentsId { get; set; }
        public string FileType { get; set; }
        public string AssetReportUrl { get; set; }
        public string LiabilityReportUrl { get; set; }
        public string CapitalReportUrl { get; set; }
        public string SalesReportUrl { get; set; }
        public string propertRightReportUrl { get; set; }
        public string FileName { get; set; }
        public bool DocumentStatus { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
    }
}
