//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeHolder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserShareSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUserShareSale()
        {
            this.tblUserShareSalesApprovers = new HashSet<tblUserShareSalesApprover>();
            this.tblUserShareTransactionHistories = new HashSet<tblUserShareTransactionHistory>();
            this.tblUsersShareSalesRequests = new HashSet<tblUsersShareSalesRequest>();
        }
    
        public int UserShareSalesId { get; set; }
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> TotalShares { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareSalesApprover> tblUserShareSalesApprovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserShareTransactionHistory> tblUserShareTransactionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsersShareSalesRequest> tblUsersShareSalesRequests { get; set; }
    }
}
